### ISSUE TITLE
Need support for http.proxy port, server and protocol 

### ISSUE THREAD

**Issue by arnold-sig** [sig-ansible/tomcat#6]
Since most of our tomcat servers are behind a load balancer, it would be immensely helpful if the role supported the http.proxy settings in the Connector tag

**Comment by dboitnot** [comment]
Can you please provide some examples of what this would look like and in which XML files?

**Comment by gillfimj** [comment]
This  would be in the server.xml:

```
  <Connector port="8080" protocol="HTTP/1.1"
               proxyPort="443" scheme="https" secure="true" proxyName="lb-or-proxy.school.edu"
               connectionTimeout="20000"
               redirectPort="8443" />
```

**Comment by dboitnot** [comment]
Is this something we could pull off with the `tomcat_connector_extra_attrs` variable?

**Comment by gillfimj** [comment]
Maybe. Wasn't really sure what that variable was for. Would it look like this:
```yaml
tomcat_connector_extra_attrs:
  - attribute: proxyPort
    value: 443
  - attribute: scheme
    value: https
  - attribute: proxyName
    value: lb-or-proxy.school.edu
```
And then that would get added to the before_ansible.sh as a /ansible/group_vars/all/dynamic_shared.yml. Am I close?
