### ISSUE TITLE
Received warning during password update for tomcat_users.xml file

### ISSUE THREAD

**Issue by gillfimj** [sig-ansible/tomcat#8]
Receiving a warning when updating a password via the tomcat_users_xml.yml:

TASK [sig-ansible.tomcat : Add Tomcat users] ***********************************
changed: [localhost] => (item={'name': 'cashconnector', 'password': '<redacted>', 'roles': 'cashnetinterface', 'append': True})
[WARNING]: Module did not set no_log for update_password
[WARNING]: Module did not set no_log for obfuscate_password

Possible update would be to add the no_log option to the tomcat_user creation:

```yaml
- name: Add Tomcat users
  tomcat_user:
    catalina_home: "{{ tomcat_root }}"
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    roles: "{{ item.roles }}"
    append: "{{ item.append }}"
  no_log: true
  with_items: "{{ tomcat_users }}"
  tags: tomcat_conf
```
